###########################
##### GENERAL CONFIG ######
###########################
application-name: 'flytosocial'

############################
##### DATABASE CONFIG ######
############################
db-type: 'sqlite'
db-address: '/gotosocial/storage/sqlite.db'

###########################
##### ACCOUNTS CONFIG #####
###########################
accounts-registration-open: false
accounts-allow-custom-css: true

########################
##### MEDIA CONFIG #####
########################
media-remote-cache-days: 7
media-emoji-local-max-size: 1024000
media-emoji-remote-max-size: 1024000

##########################
##### STORAGE CONFIG #####
##########################
storage-backend: 's3'

###########################
##### STATUSES CONFIG #####
###########################
statuses-max-chars: 5000
statuses-cw-max-chars: 200
statuses-poll-max-options: 10
statuses-poll-option-max-chars: 150
statuses-media-max-files: 10
